import adsbusca
from time import perf_counter

lista = adsbusca.gera_lista_aleatoria(10, 1, 100)
print('lista gerada')
print(lista)

print("Ordenando a lista....")
lista.sort()
print("Lista gerada")
print(lista)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                